trigger:
- main  # Trigger the pipeline when changes are made to the main branch

pool:
  vmImage: 'ubuntu-latest'  # Specify the VM image to use for the build (you can use windows-latest as well)

steps:
# Checkout the code from the Git repository
- task: Checkout@1
  displayName: 'Checkout code'

# Run your Python script (if it's a Python project) and capture the output in a text file
- script: |
    python add.py > output.txt
  displayName: 'Run Python script and save output'

# Publish the output.txt file as an artifact
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'output.txt'  # Path to the output file
    ArtifactName: 'output-artifact'  # Name of the artifact
    publishLocation: 'Container'  # Store the artifact in the pipeline container
  displayName: 'Publish output.txt as artifact'
