trigger:
  branches:
    include:
      - main  

pool:
  vmImage: 'ubuntu-latest'  

steps:
- task: Checkout@1
  displayName: 'Checkout code from GitHub'

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.11'  # Use the appropriate Python version
  displayName: 'Set up Python'

- script: |
    python -m pip install --upgrade pip
  displayName: 'Upgrade pip'

- script: |
    echo "Current working directory: $(System.DefaultWorkingDirectory)"  # Debug to check working directory
    echo "Listing files in the current directory:"
    ls -al  # List the files to confirm add.py is present
  displayName: 'Check directory contents'

- script: |
    python add.py  # Run your Python script
  displayName: 'Run Python script'

- script: |
    echo "Output is being displayed in the pipeline logs"
  displayName: 'Display output message'
