trigger:
  branches:
    include:
      - main  

pool:
  vmImage: 'ubuntu-latest'  

steps:
- task: Checkout@1
  displayName: 'Checkout code from GitHub'

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.11'  # Use the appropriate Python version
  displayName: 'Set up Python'

- script: |
    python -m pip install --upgrade pip
    # Install any dependencies if required (e.g., if you have a requirements.txt)
    # python -m pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    echo "Current working directory: $(System.DefaultWorkingDirectory)"  # Debug step to print working directory
    echo "Listing files in the current directory:"
    ls -al  # List the files in the directory to ensure add.py is present
  displayName: 'Debug step - Check directory contents'

- script: |
    python add.py  # Run your Python script
  displayName: 'Run Python script'

- script: |
    echo "Output is being displayed in the pipeline logs"  # Optional message
  displayName: 'Display output message'

