trigger:
- main  # Trigger the pipeline when code is pushed to the main branch

pool:
  vmImage: 'ubuntu-22.04'  # Use the latest Ubuntu image for the pipeline

jobs:
- job: BuildAndRun
  displayName: 'Run Python Code and Save Output'
  steps:
  
    # Step 1: Checkout the code from the repository
    - checkout: self  # Checkout task for Azure Pipelines
      displayName: 'Checkout Repository'
    
    # Step 2: Set up Python
    - task: UsePythonVersion@0  # Set up Python task
      inputs:
        versionSpec: '3.11'  # Use Python version 3.x
        addToPath: true  # Add Python to PATH
    
    # Step 3: Run the Python code and save the output
    - script: |
        python add.py > output.log 2>&1  # Run the code and save both stdout and stderr to output.log
      displayName: 'Run add.py and Save Output'

    # Step 4: Publish the output as an artifact
    - publish: $(System.DefaultWorkingDirectory)/output.log  # Path to the output file
      artifact: python-output  # Name of the artifact
      displayName: 'Publish Output as Artifact'
