trigger:
- main  # Trigger the pipeline on push to the main branch (change if needed)

pool:
  vmImage: 'ubuntu-latest'  # Use Ubuntu as the build environment (you can choose other OS)

steps:
- task: Checkout@1  # Checkout the code from the repository

- task: UsePythonVersion@0  # Setup Python version
  inputs:
    versionSpec: '3.11'  # Specify the Python version you want (e.g., 3.x)

- script: |
    python -m pip install --upgrade pip  # Upgrade pip
    #pip install -r requirements.txt  # Install dependencies (if any)
  displayName: 'Install dependencies'

- script: |
    python add.py > output.log   # Run the Python script and save output to output.log
  displayName: 'Run Python Script'

- task: PublishBuildArtifacts@1  # Publish the output log as an artifact
  inputs:
    PathtoPublish: 'output.log'  # Path to the output log file
    ArtifactName: 'output-log'  # Name of the artifact
    publishLocation: 'Container'  # Publish location for the artifact
