trigger:
- main 
pool:
  vmImage: 'ubuntu-22.04' 

jobs:
- job: BuildAndRun
  displayName: 'Run Python Code and Save Output'
  steps:
 
    - checkout: self 
      displayName: 'Checkout Repository'
    
   
    - task: UsePythonVersion@0 
      inputs:
        versionSpec: '3.11'
        addToPath: true  
 
    - script: |
        python add.py > output.log 2>&1  # Run the code and save both stdout and stderr to output.log
      displayName: 'Run add.py and Save Output'

    - publish: $(System.DefaultWorkingDirectory)/output.log 
      artifact: python-output
      displayName: 'Publish Output as Artifact'
